### ISSUE TITLE
Backups not automatically deleting

### ISSUE THREAD

**Issue by lewishackfath** [eduardoestrella/cPanel-automated-system-backup#1]
Hello,

I ran the script to test functionality and have discovered that my backups are not being deleted automatically.

I ran the script every hour to test this and currently have 9 backups sitting in my daily folder but the limit I have set is 5.

thanks in advnace.

**Comment by eduardoestrella** [comment]
Hi,

Has got the FTP user delete permission? anyway, I will check the delete feature on this days.

Thanks for reporting it.

**Comment by eduardoestrella** [comment]
@lewishackfath I released version 1.1 (I started to version right now, you have 1.0) I refactor some code so please download again the script, dependencies and configure the new file ```config.php``` you can use the previous data configuration in ```index.php```

Say that you can activate Debug mode if you need to get more info about what is happening.

In your current scenario would be necessary to delete manually the extra backups, I mean if you set 5 the limit of daily backups and now you have 8 backups, remove 3 of them and set the total in 5. Do this before to run the script version 1.1

I was testing version 1.1 and now is deleting correctly, if you continue with any problem let me know.
