### ISSUE TITLE
daily, monthly and yearly directories

### ISSUE THREAD

**Issue by ghost** [eduardoestrella/cPanel-automated-system-backup#2]
The three directories don't seem to be created when the script is run. Additionally if I create the 3 directories manually and then run the script, it seems that those directories are counted like actual backup files.

**Comment by eduardoestrella** [comment]
Hi there,

I will try to reproduce it and tell you more then.

**Comment by eduardoestrella** [comment]
I couldn't reproduce. Which version are you using? 
The bug about create folder was fixed in v1.1 and counted backup files since v1.2 (I just did the release ;))

**Comment by ghost** [comment]
Hi. I am using v1.1. I just checked the script on the server.
I will use the new v1.2 script see how things go. :)
