### ISSUE TITLE
Reporting Erroneous information

### ISSUE THREAD

**Issue by ghost** [eduardoestrella/cPanel-automated-system-backup#3]
I have used the script with 2 different hosting compagnies and both work apart from the issue I reported earlier. However in one of the instances I get the following errors in the log:

`cPanel automated system backup - Version 1.1</br>Couldn't connect to [domain.com:21]</br>Login Error </br>Folder /Backup_WEB/daily created</br>Folder /Backup_WEB/monthly created</br>Folder /Backup_WEB/yearly created</br>Daily Backup not Found in remote FTP [/Backup_WEB/daily] folder</br>API cPanel FullBackup launched</br>Creating and Uploading new Backup to [domain.com:21]</br>When finished the upload to remote FTP an email notification will be send to [email@email.com]</br>`

As you can see there is a 'Couldn't connect to' and 'login error' reported however the backup is properly done and uploaded to the ftp server. I am unsure why this is happening but all I can say is that the backup is done.

[I have purposely edited domain and email info for security reasons.]

**Comment by eduardoestrella** [comment]
Hi,

Please review your FTP setting. The script is separate in 2 part, first connect to FTP and manage the backups files, the second one connect to cPanel API and run the backup task in the hosting (when this is finished, cpanel send via FTP the backup).

Both aren't linked, so if the first part fails the second can be launched without problem. That could be the reason your backup was done but the log said that there is a problem with the FTP.

**Comment by ghost** [comment]
Hi,

The FTP settings are fine else the backup would not be uploaded to the FTP server. So the script is reporting that it could not connect but the fact is that it did AND successfully uploaded the backup. Weird.

**Comment by ghost** [comment]
By curiosity I went and looked at the server error_log. I found this at each instance that the script has run in the past. The one below is the one from today's  backup:

> [01-Apr-2018 02:00:02 America/Denver] PHP Warning:  ftp_connect() has been disabled for security reasons in /home/usernetxp/scripts/index.php on line 26
> [01-Apr-2018 02:00:02 America/Denver] PHP Warning:  ftp_login() has been disabled for security reasons in /home/usernetxp/scripts/index.php on line 35
> [01-Apr-2018 02:00:02 America/Denver] PHP Warning:  ftp_pasv() expects parameter 1 to be resource, null given in /home/usernetxp/scripts/index.php on line 36
> [01-Apr-2018 02:00:02 America/Denver] PHP Warning:  ftp_mkdir() expects parameter 1 to be resource, null given in /home/usernetxp/scripts/index.php on line 46
> [01-Apr-2018 02:00:02 America/Denver] PHP Warning:  ftp_mkdir() expects parameter 1 to be resource, null given in /home/usernetxp/scripts/index.php on line 51
> [01-Apr-2018 02:00:02 America/Denver] PHP Warning:  ftp_mkdir() expects parameter 1 to be resource, null given in /home/usernetxp/scripts/index.php on line 56
> [01-Apr-2018 02:00:02 America/Denver] PHP Warning:  ftp_chdir() expects parameter 1 to be resource, null given in /home/usernetxp/scripts/index.php on line 62
> [01-Apr-2018 02:00:02 America/Denver] PHP Warning:  ftp_nlist() expects parameter 1 to be resource, null given in /home/usernetxp/scripts/index.php on line 63
> [01-Apr-2018 02:00:02 America/Denver] PHP Warning:  ftp_close() expects parameter 1 to be resource, null given in /home/usernetxp/scripts/index.php on line 114

I guess the problem is coming from the hosting company.

**Comment by eduardoestrella** [comment]
Yes, it seems a hosting problem. I will close the issue, if not a hosting problem open a new one. Thanks for using the script :)
