### ISSUE TITLE
Add local backup support ?

### ISSUE THREAD

**Issue by madIlama** [eduardoestrella/cPanel-automated-system-backup#4]
# How about local backup support?

since this script is installed on remote (different server from cpanel server), it will be viable option to cut the bridge server

current diagram :

` cpanel.server --> cp.asb-bridge.server --> ftp.backup.server `

suggested local option :

` cpanel.server --> cp.asb-backup.server `

in addition, i currently use this (ftping to local) with rclone ,  it even more awesome if rclone command supported

**Comment by eduardoestrella** [comment]
Hi there!

I'm sorry but I really don't get your point about the bridge server with the current diagram on the local suggested.

I will comment what the script is doing in short steps. Please, take this steps to explain me your point about local option.

0. The cron job execute the script
1. FTP Operations. The script connects to the remote FTP where are the backups and manage the backups moving or deleting it throw daily, monthly or yearly folders.
2. Cpanel Backup. The script connects to cPanel and launch the backup command using the cPanel API, when the backup is finished then cPanel connect to the remote FTP and upload the backup and notify by email. In this part cPanel is who do all the work, the script only call to cpanel to say "start with the backup".

About **rclone** I have to say that would be a great feature to implement but it's not me who have to do it, is cPanel. Like I said in step 2 cPanel is who create the backup and upload it using FTP protocol. Cpanel not support rclone.

**Comment by sahilgillsg** [comment]
@eduardoestrella how to export cPanel full backup using API2, UAPI?

**Comment by eduardoestrella** [comment]
@sahilgillsg I only use API1, but when I was reading API2 doc I didn't find nothing about full backup.
