### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by dvsqrd** [eduardoestrella/cPanel-automated-system-backup#5]
When trying to execute index.php an error is logged.

`PHP Parse error:  syntax error, unexpected '=' in /home/user/public_html/backup/index.php on line 134`

The error seems to clear when I change `json` to `$json`. It then writes output to the log file, however no backup appears to be made and no transfer is occuring on the FTP server

> [2018-11-19 10:54:02.849786] [info] ----------------------------------------------
> [2018-11-19 10:54:02.849904] [info] cPanel automated system backup - Version 1.2
> [2018-11-19 10:54:03.331578] [debug] Connected to [ftp.domain.example:21]
> [2018-11-19 10:54:04.073832] [debug] User [ftp_username] Logged
> [2018-11-19 10:54:05.077395] [debug] Daily Backup not Found in remote FTP [/cPanel/daily] folder
> [2018-11-19 10:54:05.238044] [info] API cPanel FullBackup launched
> [2018-11-19 10:54:05.238094] [info] Creating and Uploading new Backup to [ftp.domain.example:21]
> [2018-11-19 10:54:05.238102] [info] When finished the upload to remote FTP an email notification will be send to [email@domain.example]

**Comment by eduardoestrella** [comment]
Hi!

You are right, I will fix now. 

The action of creating and upload the backup to the FTP server is doing by cPanel, so if something is failing there I have no way to know it, sorry.

Thank you!
