### ISSUE TITLE
Getting Hash Error

### ISSUE THREAD

**Issue by pasayev** [eduardoestrella/cPanel-automated-system-backup#6]
Hello,

In log I get following error.

[error] API cPanel FullBackup Error: HASH(0x33577e0)

**Comment by eduardoestrella** [comment]
Hi,

This error is the error that your server is sending. 

Anyway, confirm that your server support the cPanel API 1

**Comment by pasayev** [comment]
Hi,
Cpanel version is 100.0.5. I think API 1 is depreciated. Are you going to plan to update project for API 2 ? Thank you.

**Comment by eduardoestrella** [comment]
Hey,

I am not planning to update because I don't use cPanel currently, so I don't need it. Sorry :(
